### ISSUE TITLE
undefined method `entries' for nil:NilClass

### ISSUE THREAD

**Issue by plentz** [devunwired/apktools#18]
```ruby
apk = ApkXml.new("GPS-Status-Toolbox-PRO_7.1.142-Android-1.com.apk")
apk.parse_xml("AndroidManifest.xml", true, true)
```

```
NoMethodError: undefined method `entries' for nil:NilClass
	from /usr/local/lib/ruby/gems/2.3.0/gems/apktools-0.7.1/lib/apktools/apkresources.rb:307:in `get_resource_value'
	from /usr/local/lib/ruby/gems/2.3.0/gems/apktools-0.7.1/lib/apktools/apkresources.rb:266:in `get_default_resource_value'
	from /usr/local/lib/ruby/gems/2.3.0/gems/apktools-0.7.1/lib/apktools/apkxml.rb:234:in `parse_xml'
	from (irb):11
```

**Comment by plentz** [comment]
[GPS-Status-Toolbox-PRO_7.1.142-Android-1.com.apk.zip](https://github.com/devunwired/apktools/files/331909/GPS-Status-Toolbox-PRO_7.1.142-Android-1.com.apk.zip)
